name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Create config file
      run: |
        echo "const config = { GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}' };" > config.js
      
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Deploy to gh-pages
      run: |
        git checkout --orphan gh-pages
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages 